<div class="form-group">
  <label class="col-sm-3 control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
  <div class="col-sm-8">
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  </div>
  <div class="col-sm-1"></div>
</div>
<div class="form-group">
  <label class="col-sm-3 control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
  <div class="col-sm-8">
    <input type="password" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control"/>
  </div>
  <div class="col-sm-1"></div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_forgot_password">
        <a href="https://obv-at-oeaw.alma.exlibrisgroup.com/view/resetPw?institutionCode=43ACC_OEAW" target="_blank" id="login_forgot_password"><?=$this->transEsc('Forgot Password')?></a>
    </label>
    <div class="col-sm-1"></div>
</div>