<div id="systemChangeAlert2" style="display: none;">
	<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>&nbsp;
	Login nicht möglich!&nbsp;
	<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
	<br />
	Systemumstieg vom 22.12.17 - 7.1.18!
</div>

<? $account = $this->auth()->getManager(); ?>
<? $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<? if (!$sessionInitiator): // display default login form if no login URL provided ?>
  <form method="post" class="form-horizontal" action="<?=$this->url('myresearch-home')?>" name="loginForm" id="loginForm">
    <?=$this->auth()->getLoginFields()?>
    <input type="hidden" name="auth_method" value="<?=$account->getAuthMethod()?>">
    <div class="form-group">
    <?php
    $loginFormLink = isset($this->addLink['text']) && (isset($this->addLink['url'])); // AKsearch specific
    $creationLink = $account->supportsCreation(); // VuFind specific
    $recoveryLink = $account->supportsRecovery(); // VuFind specific
    if ($loginFormLink || $creationLink || $recoveryLink) {
        echo '<div class="col-sm-offset-3 col-sm-4">';
        if ($loginFormLink) {
            echo '<a class="btn btn-primary" href="'.$this->addLink['url'].'" target="'.$target.'">'.$this->transEsc($this->addLink['text']).'</a>';
        }
        /*
        if ($creationLink) {
            echo '<a class="btn btn-link createAccountLink" href="'.$this->url('myresearch-account').'?auth_method='.$account->getAuthMethod().'">'.$this->transEsc('Create New Account').'</a>';
        }
        if ($recoveryLink) {
            echo '<a class="btn btn-link" href="'.$this->url('myresearch-recover').'?auth_method='.$account->getAuthMethod().'">'.$this->transEsc('Forgot Password').'</a>';
        }
        */
        echo '</div>';
        
        echo '<div class="col-sm-4">';
            echo '<input class="btn btn-primary" type="submit" name="processLogin" value="'.$this->transEsc('Login').'" style="float: right;">';
        echo '</div>';
    } else {
        echo '<div class="col-sm-11">';
            echo '<input class="btn btn-primary" type="submit" name="processLogin" value="'.$this->transEsc('Login').'" style="float: right;">';
        echo '</div>';
    }
	?>

    </div>
  </form>
<? else: ?>
  <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><?=$this->transEsc("Institutional Login")?></a>
<? endif; ?>