<?
    // Set up page title:
    $this->headTitle($this->translate('Change UserData'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>' . '<li class="active">' . $this->transEsc('Change UserData') . '</li>';
?>
<? if ($this->auth()->isLoggedIn()): ?>
  <div class="row">
    <div class="<?=$this->layoutClass('mainbody')?>">
<? endif; ?>

<h2><?=$this->transEsc('Change UserData') ?></h2>
<?=$this->flashmessages() ?>

<? if (!$this->auth()->getManager()->supportsUserDataChange($this->auth_method)): ?>
  <div class="error"><?=$this->transEsc('change_userdata_disabled') ?></div>
<? elseif (!isset($this->hash)): ?>
  <div class="error"><?=$this->transEsc('recovery_user_not_found') ?></div>
<? else: ?>	
  <form id="changeUserData" class="form-horizontal" action="<?=$this->url('aksites-changeuserdata') ?>" method="post" data-toggle="validator" role="form">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->hash) ?>" name="hash"/>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->username) ?>" name="username"/>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth_method) ?>" name="auth_method"/>
    
    <div>
    	<?=$this->auth()->getChangeUserDataForm() ?>
    </div>
    
    <div class="form-group">
      <div class="col-sm-9 col-sm-offset-3">
        <?=$this->recaptcha()->html($this->useRecaptcha) ?>
      </div>
    </div>
    
    <div>
	    <table class="table">
	    	<tr>
	    		<td>
	    			<input class="btn btn-primary" name="cancel" type="submit" value="<?=$this->transEsc('Cancel')?>" />
	    		</td>
	    		<td align="right">
	    			<input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEsc('Submit')?>" />
	    		</td>
	    	</tr>
	    </table>
    </div>
  </form>

  
      
<? endif; ?>


<? if ($this->auth()->isLoggedIn()): ?>
    </div>
    <div class="<?=$this->layoutClass('sidebar')?>">
      <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'changeuserdata'))?>
    </div>
  </div>
<? endif; ?>
