<?php
// Set up page title:
$this->headTitle($this->translate('User Account'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Account') . '</li>';

// Show texts
echo '<h2>'.$this->transEsc('User Account').'</h2>';
echo $this->flashmessages();
echo $this->transEsc('accountAddedSuccessfullyText');
?>