<h3>Datenschutzerklärung</h3>

<h4>Gespeicherte Daten</h4>

<p>
AKsearch speichert und verarbeitet folgende personenbezogene Daten, wenn Sie unsere Website besuchen:
</p>

<p>
<strong>Serverlogs: </strong>Die IP-Adresse des Anfragenden Computers, gemeinsam mit dem Datum, der Uhrzeit, der Anfrage, welche Datei angefragt wird (Name und URL), welche Datenmenge an Sie übertragen wird, eine Meldung, ob die Anfrage erfolgreich war, Erkennungsdaten des verwendeten Browsers und des verwendeten Betriebssystems, sowie die Website, von der der Zugriff erfolgte (sollte der Zugriff über einen Link erfolgen). Die Serverlogs werden gespeichert, um die Systemsicherheit prüfen zu können, die Website technisch administrieren, sowie das Angebot optimieren zu können. Diese Daten werden – sollte es einen Hackangriff gegeben haben – an die Strafverfolgungsbehörden weitergeben. Eine darüberhinausgehende Weitergabe an Dritte erfolgt nicht.
</p>

<p>
<strong>Cookies: </strong>Cookies sind kleine Textdateien, die AKsearch auf dem Computer des Benutzers speichert, um diesen wiederzuerkennen. So dienen die in den Cookies enthaltenen Informationen der Sitzungssteuerung. Bei den meisten Web-Browsern werden Cookies automatisch akzeptiert. Durch Änderung der Einstellungen Ihres Browsers können Sie dies vermeiden. Sie können auf Ihrem PC gespeicherte Cookies jederzeit durch Löschen der temporären Internetdateien entfernen.
</p>

<p>
<strong>Piwik: </strong>AKsearch nutzt Piwik, mit der durch Cookies eine Analyse der Nutzung von AKsearch durchgeführt werden kann. Dazu werden die Nutzungsinformationen an AKsearch gesendet, wobei Ihre IP-Adresse sofort anonymisiert wird. Eine Weitergabe der Daten an Dritte erfolgt nicht, personenbezogene Daten werden nicht gespeichert. Von Piwik genutzte Cookies beginnen mit „_pk_ref“, „_pk_cvar“, „_pk_id“ und „_pk_ses“.
<br />
Sollten Sie eine Auswertung nicht wünschen, klicken Sie bitte auf folgenden Link: https://piwik.arbeiterkammer.at/index.php?module=CoreAdminHome&action=optOut&language=de
Dabei wird ein Cookie in Ihrem Browser hinterlegt, dieses verhindert, dass Ihre Besuchsdaten an unseren Statistik Server übertragen werden. Sollten Sie Ihre Browser Cookies löschen so müssen Sie die Auswertung erneut deaktivieren.
initVuFindPiwikTracker


<p>
<iframe style="border: 0; height: 200px; width: 600px;" src="http://localhost/piwik/index.php?module=CoreAdminHome&action=optOut&language=de"></iframe>
</p>


</p>