<?
// Set up page title:
$this->headTitle($this->translate('loanHistory'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>' . '<li class="active">' . $this->transEsc('loanHistory') . '</li>';

// Get view variable
$chkOptInLoanHistory = $this->chkOptInLoanHistory;

?>
<? if ($this->auth()->isLoggedIn()): ?>
  <div class="row">
    <div class="<?=$this->layoutClass('mainbody')?>">
<? endif; ?>

<h2><?=$this->transEsc('loanHistory') ?></h2>
<?=$this->flashmessages() ?>

<? if (!$this->auth()->getManager()->supportsLoanHistory($this->auth_method)): ?>
  <div class="error"><?=$this->transEsc('loanHistoryDisabled') ?></div>
<? else: ?>	

	<? if (isset($this->loanHistory['isLoanHistory']) && $this->loanHistory['isLoanHistory'] == false):?>
		<?=$this->transEsc('loanHistoryOptInText')?>
		<br /><br />
		<form name="optInLoanHistory" id="optInLoanHistory" method="post">
			<table id="tblOptInLoanHistory">
				<tr>
					<td nowrap="nowrap" style="padding: 15px;"><input type="checkbox" id="chkOptInLoanHistory" name="chkOptInLoanHistory" <?=(($chkOptInLoanHistory == 1) ? 'checked="checked"' : '')?>/></td>
					<td width="100%"><label for="chkOptInLoanHistory" style="margin-bottom: 0px;"><?=$this->transEsc('loanHistoryOptInCheckbox')?></label></td>
					<td nowrap="nowrap"><input type="submit" class="btn btn-default" style="width: 55px;" name="submitOptIn" value="<?=$this->transEsc("OK")?>" /></td>
				</tr>			
	        </table>
		</form>
	<? elseif (!empty($this->loanHistory) && !isset($this->loanHistory['isLoanHistory'])): ?>
		<form name="exportLoanHistory" id="exportLoanHistory" method="post">
	        <div class="toolbar">
	          <input type="submit" class="btn btn-default" name="submit" value="<?=$this->transEsc("exportLoanHistory")?>" />
	        </div>
	        <br />
        </form>
        
		<? if ($this->paginator): ?>
	        <?=$this->transEsc("Showing")?>
	        <? $start = $this->paginator->getAbsoluteItemNumber(1);
	        $end = $this->paginator->getAbsoluteItemNumber($this->paginator->getItemCountPerPage());
	        $total = $this->paginator->getTotalItemCount();
	        ?>
	        <strong><?=$this->localizedNumber($start)?></strong> - <strong><?=$this->localizedNumber($end > $total ? $total : $end)?></strong>
	        <?=$this->transEsc('of')?> <strong><?=$this->localizedNumber($total)?></strong>
      	<? endif; ?>
		
		<? $i = 0; foreach ($this->loanHistory as $resource): ?>
		
        <hr/>
        <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="row">
          <? $cover = $this->record($resource)->getCover('checkedout', 'small'); ?>
          
          <? if ($cover): ?>
            <div class="col-sm-2 text-center">
            <? /* Display thumbnail if appropriate: */ ?>
              <?=$cover?>
            </div>
            <div class="col-sm-6">
         <? else: ?>
            <div class="col-sm-9">
         <? endif; ?>

            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource) . '" class="title">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
              <strong><?=$this->transEsc('by')?>:</strong> 
              <a href="<?=$this->record($resource)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
            <? endif; ?>
            
            
            
            <? if (!empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('location_' . $ilsDetails['institution_name'], array(), $ilsDetails['institution_name'])?></strong>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEsc('location_' . $ilsDetails['borrowingLocation'], array(), $ilsDetails['borrowingLocation'])?>
              <br />
            <? endif; ?>
            
            <? if (!empty($ilsDetails['duedate'])): ?>
            	<strong><?=$this->transEsc('Due Date')?>:</strong> <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?>
            <? endif; ?>

            <? if (isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <? endif; ?>

          </div>
        </div>
        
      <? endforeach; ?>
      <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
	
	<? else: ?>
      <?=$this->transEsc('noLoanHistoryFound')?>
    <? endif; ?>
 
<? endif; ?>

<? if ($this->auth()->isLoggedIn()): ?>
    </div>
    <div class="<?=$this->layoutClass('sidebar')?>">
      <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'loanhistory'))?>
    </div>
  </div>
<? endif; ?>