<?
    // Set up page title:
    $this->headTitle($this->translate('requestSetPasswordHeading'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>' . '<li class="active">' . $this->transEsc('requestSetPasswordHeading') . '</li>';
?>

<h2><?=$this->transEsc('requestSetPasswordHeading') ?></h2>
<?=$this->flashmessages() ?>

<div>
<?php
echo $this->translate('requestSetPasswordText');
?>
</div>

<form id=requestSetPassword class="form-horizontal" action="<?=$this->url('aksites-requestsetpassword') ?>" method="post" data-toggle="validator" role="form">    
    <div>
    	<?=$this->auth()->getRequestSetPasswordForm() ?>
    </div>
    
    <div>
	    <table class="table">
	    	<tr>
	    		<td>
	    			<a href="<?= $this->url('home') ?>" id="cancel" name="cancel" class="btn btn-default"><?=$this->transEsc('Cancel')?></a>
	    		</td>
	    		<td align="right">
	    			<input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEsc('Submit')?>" />
	    		</td>
	    	</tr>
	    </table>
    </div>
  </form>