<?
    // Set up page title:
    $this->headTitle($this->translate('setPasswordWithOtp'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>' . '<li class="active">' . $this->transEsc('setPasswordWithOtp') . '</li>';
?>

<h2><?=$this->transEsc('setPasswordWithOtp') ?></h2>
<?=$this->flashmessages() ?>

<form id=setPasswordWithOtp class="form-horizontal" action="<?=$this->url('aksites-setpasswordwithotp') ?>" method="post" data-toggle="validator" role="form">    
    <div>
    	<?=$this->auth()->getSetPasswordWithOtpForm() ?>
    </div>
    
    <div class="form-group">
      <div class="col-sm-9 col-sm-offset-3">
        <?=$this->recaptcha()->html($this->useRecaptcha) ?>
      </div>
    </div>
    
    <div>
	    <table class="table">
	    	<tr>
	    		<td>
	    			<input class="btn btn-primary" name="cancel" type="submit" value="<?=$this->transEsc('Cancel')?>" />
	    		</td>
	    		<td align="right">
	    			<input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEsc('Submit')?>" />
	    		</td>
	    	</tr>
	    </table>
    </div>
  </form>
  