<?php
// Set up page title:
$this->headTitle($this->translate('Create New Password'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Create New Password') . '</li>';

// Show texts
echo '<h2>'.$this->transEsc('Create New Password').'</h2>';
echo $this->flashmessages();
echo $this->transEsc('setPasswordSuccessText');
?>