<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
      // Set global path for Javascript code:
      $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

      // Deal with cart stuff:
      if (!isset($this->renderingError)) {
        $cart = $this->cart();
        $this->jsTranslations()->addStrings(
          array(
          	'add_tag_success' => 'add_tag_success',
            'bulk_email_success' => 'bulk_email_success',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'loading' => 'Loading',
            'sms_success' => 'sms_success'
          )
        );
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $this->jsTranslations()->addStrings(
            array(
              'bulk_noitems_advice' => 'bulk_noitems_advice',
              'confirmDelete' => 'confirm_delete',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'viewBookBag' => 'View Book Bag',
              'addBookBag' => 'Add to Book Bag',
              'removeBookBag' => 'Remove from Book Bag',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagStatusFull' => 'bookbag_full',
            )
          );
        }
        $this->headScript()->appendScript($this->jsTranslations()->getScript());
        
        // Added by AK Bibliothek Wien
        $this->headScript()->appendScript(
        	'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
        );
      }

      // Session keep-alive
      if ($this->KeepAlive()) {
          $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
          $this->headScript()->appendFile("keep_alive.js");
      }
    ?>
    <?php
      $dsb = null;
      $translations = null;
      $root = rtrim($this->url('home'), '/');
      $setupJS = <<<JS
VuFind.path = '{$root}';
VuFind.defaultSearchBackend = '{$dsb}';
VuFind.addTranslations({$translations});
JS;
      $this->headScript()->appendScript($setupJS);
    ?>
    
    <?=$this->headScript()?>
    
  </head>
  <body>
  
  
  

  
    <? // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
    <header role="banner" class="hidden-print">
      
      <div class="container navbar">
        <a class="sr-only" href="#content"><?=$this->transEsc('Skip to content') ?></a>  
        <?=$this->render('header.phtml')?>
      </div>
      
    		<?php
    		echo '<section class="visible-lg">';
    			echo $this->layout()->searchbox;
    		echo '</section>';
    		?>
    		<nav class="nav searchbox hidden-lg hidden-print">
	          <?=$this->layout()->searchbox ?>
	    	</nav>

        
        <? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
          && !empty($this->layout()->breadcrumbs)
          && $this->layout()->breadcrumbs !== false
        ): ?>
          <ul class="breadcrumb hidden-print">
	          <div class="container">
	          <? if(is_array($this->layout()->breadcrumbs)): ?>
	            <? if(count($this->layout()->breadcrumbs) > 1): ?>
	              <?=$this->render('breadcrumbs/multi.phtml', array(
	                  'parents' => $this->layout()->breadcrumbs,
	                  'title'   => $this->layout()->title,
	                  'end'     => $this->layout()->breadcrumbEnd,
	                  'from'    => $this->layout()->from
	                )) ?>
	            <? else: ?>
	              <?=$this->render('breadcrumbs/default.phtml', array(
	                  'parents' => $this->layout()->breadcrumbs,
	                  'title'   => $this->layout()->title
	                )) ?>
	            <? endif; ?>
	          <? else: ?>
	            <?=$this->layout()->breadcrumbs ?>
	          <? endif; ?>
	          </div>
          </ul>
        <? endif; ?>

    </header>
    
    <div role="main" class="main">

    <?php
    if ($this->layout()->templateDir == 'search' && $this->layout()->templateName == 'home') {
        echo '<div class="akContainer">';
        echo $this->layout()->content;
        echo '</div>';
        
        echo	'<div id="systemChangeAlert2">'.
                    '<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>&nbsp;'.
                    'Einschränkung wegen Systemumstieg, 22.12.17 - 7.1.18: '.
                    '<a href="https://wien.arbeiterkammer.at/service/bibliothek/systemumstieg.html" target="_blank">Weitere Infos hier</a>!'.
                '</div>';
        
    } else {
        
        echo	'<div id="systemChangeAlert2">'.
                    '<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>&nbsp;'.
                    'Einschränkung wegen Systemumstieg, 22.12.17 - 7.1.18: '.
                    '<a href="https://wien.arbeiterkammer.at/service/bibliothek/systemumstieg.html" target="_blank">Weitere Infos hier</a>!'.
                '</div>';
        
        echo '<div class="container">';
        echo $this->layout()->content;
        echo '</div>';
    }

    /*
    	if ($this->layout()->templateDir == 'search' && $this->layout()->templateName == 'home') {
    		echo '<div class="akContainer">';
    			echo $this->layout()->content;
    		echo '</div>';
    	} else {
    		echo '<div class="container">';
    			echo $this->layout()->content;
    		echo '</div>';
    	}
    */
    ?>

    </div>
    <div>
    
    <?php
		if ($this->layout()->templateDir == 'search' && $this->layout()->templateName == 'home') {

			if ($this->layout()->userLang == 'de') { // German version
				echo '<div class="akFeatureIntro">';
					
				//echo '<div id="akFeatureIntroHeader" class="akFeatureIntroHideRight">AKsearch</div>';
				echo '<div id="akFeatureIntroSubHeader" class="akFeatureIntroHideRight">Neue Suchmaschine der AK Bibliothek Wien</div>';
					
				echo '<div id="akFeatureIntroContentBox1" class="akFeatureIntroHideLeft akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader akTextAlignRight">';
				echo 'Moderne Suchoberfläche <i class="fa fa-chevron-down" aria-hidden="true"></i>';
				echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText akRight">';
				echo '<ul>';
				echo '<li>Zeitgemäßes Layout</li>';
				echo '<li>Auf mobilen Endgeräten verwendbar</li>';
				echo '<li>Erhöhte Benutzerfreundlichkeit</li>';
				echo '<li><a href="https://github.com/AKBibliothekWien/aksearch" target="_blank">Open Source Software</a></li>';
				echo '</ul>';
				echo '</div>';
				echo '<div class="akClearer"></div>';
				echo '</div>';
				
				echo '<div id="akFeatureIntroContentBox2" class="akFeatureIntroHideRight akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader">';
				echo '<i class="fa fa-chevron-down" aria-hidden="true"></i> Erweiterte Suchmöglichkeiten';
				echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText">';
				echo '<ul>';
				echo '<li>Filter zum Einschränken Ihrer Suchergebnisse</li>';
				echo '<li><a href="'.$this->url('help-home').'?topic=search" title="'.$this->transEsc('Search Tips').'" class="help-link">Zusätzliche Suchoperatoren</a> für zielgerichtetes Suchen</li>';
				echo '<li><a href="/Browse/Home">Stöbern in unserem Bestand</a> nach verschiedenen Gesichtspunkten</li>';
				echo '<li>Anzeigen unserer <a href="/Search/NewItem">Neuerwerbungen</a></li>';
				echo '</ul>';
				echo '</div>';
				echo '<div class="akClearer"></div>';
				echo '</div>';
				
				echo '<div id="akFeatureIntroContentBox3" class="akFeatureIntroHideLeft akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader akTextAlignRight">';
				echo 'Mehrere Quellen durchsuchen <i class="fa fa-chevron-down" aria-hidden="true"></i>';
				echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText akRight">';
				echo '<p style="text-align: right;">Duchsuchen Sie neben unserem Bibliotheksbestand zusätzliche Quellen.<br />Sie finden sogar unselbständig erschienene Texte (einzelne Zeitschriftenartikel und Buchkapitel).</p>';
				echo '<ul class="akRight">';
				echo '<li>Komplettes <a href="http://www.ssoar.info/" target="_blank">SSOAR</a> (Social Science Open Access Repository)</a></li>';
				echo '<li>Themenrelevante Inhalte des <a href="https://doaj.org/" target="_blank">DOAJ</a> (Directory of Open Access Journals)</li>';
				echo '<li><a href="https://emedien.arbeiterkammer.at/" target="_blank">eMedien der AK Wien</a></li>';
				echo '<li>Weitere Quellen werden folgen ...</li>';
				echo '</ul>';
				echo '</div>';
				echo '<div class="akClearer"></div>';
				echo '</div>';
				
				echo '<div id="akFeatureIntroContentBox4" class="akFeatureIntroHideRight akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader">';
				echo '<i class="fa fa-chevron-down" aria-hidden="true"></i> Ersatz für alten Katalog';
				echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText">';
				echo '<ul>';
				echo '<li>AKsearch ersetzt unseren alten <a href="https://aleph22-prod-sh2.obvsg.at/F?func=find-b-0&CON_LNG=ger&local_base=akw01" target="_blank">Katalog (OPAC)</a></li>';
				echo '<li>Ab Anfang 2018 wird der OPAC durch einen Softwareumstieg abgestellt</li>';
				echo '<li>Parallelbetrieb von AKsearch und OPAC bis Ende 2017</li>';
				echo '</ul>';
				echo '</div>';
				echo '<div class="akClearer"></div>';
				echo '</div>';
				
				echo '</div>';
					
				echo '<hr/>';
			} else { // All other languages
				echo '<div class="akFeatureIntro">';
					
				//echo '<div id="akFeatureIntroHeader" class="akFeatureIntroHideRight">AKsearch</div>';
				echo '<div id="akFeatureIntroSubHeader" class="akFeatureIntroHideRight">New search engine of the AK Library of Vienna</div>';
					
				echo '<div id="akFeatureIntroContentBox1" class="akFeatureIntroHideLeft akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader akTextAlignRight">';
				echo 'Modern user interface<i class="fa fa-chevron-down" aria-hidden="true"></i>';
				echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText akRight">';
				echo '<ul>';
				echo '<li>Contemporary layout</li>';
				echo '<li>Usable on mobile devices</li>';
				echo '<li>Better overall usability</li>';
				echo '<li><a href="https://github.com/AKBibliothekWien/aksearch" target="_blank">Open Source Software</a></li>';
				echo '</ul>';
				echo '</div>';
				echo '<div class="akClearer"></div>';
				echo '</div>';
				
				echo '<div id="akFeatureIntroContentBox2" class="akFeatureIntroHideRight akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader">';
				echo '<i class="fa fa-chevron-down" aria-hidden="true"></i> Additional search possibilities';
				echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText">';
				echo '<ul>';
				echo '<li>Filter your search results</li>';
				echo '<li><a href="'.$this->url('help-home').'?topic=search" title="'.$this->transEsc('Search Tips').'" class="help-link">Additional search operators</a> for precise searching</li>';
				echo '<li><a href="/Browse/Home">Browse our catalog</a></li>';
				echo '<li>Show our <a href="/Search/NewItem">new acquisitions</a></li>';
				echo '</ul>';
				echo '</div>';
				echo '<div class="akClearer"></div>';
				echo '</div>';
				
				echo '<div id="akFeatureIntroContentBox3" class="akFeatureIntroHideLeft akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader akTextAlignRight">';
				echo 'Search multiple sources <i class="fa fa-chevron-down" aria-hidden="true"></i>';
				echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText akRight">';
				echo '<p style="text-align: right;">Besides our library collection, you can search in multiple other sources.<br />You are also able to find single journal articles and book chapters.</p>';
				echo '<ul class="akRight">';
				echo '<li>Complete <a href="http://www.ssoar.info/" target="_blank">SSOAR</a> (Social Science Open Access Repository)</a></li>';
				echo '<li>Relevant contents of <a href="https://doaj.org/" target="_blank">DOAJ</a> (Directory of Open Access Journals)</li>';
				echo '<li><a href="https://emedien.arbeiterkammer.at/" target="_blank">eMedia of the Chamber of Labour of Vienna</a></li>';
				echo '<li>More sources will be added ...</li>';
				echo '</ul>';
				echo '</div>';
				echo '<div class="akClearer"></div>';
				echo '</div>';
				
				echo '<div id="akFeatureIntroContentBox4" class="akFeatureIntroHideRight akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader">';
				echo '<i class="fa fa-chevron-down" aria-hidden="true"></i> Replacement for old catalog';
				echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText">';
				echo '<ul>';
				echo '<li>AKsearch will replace our <a href="https://aleph22-prod-sh2.obvsg.at/F?func=find-b-0&CON_LNG=ger&local_base=akw01" target="_blank">catalog (OPAC)</a></li>';
				echo '<li>Due to a new software the OPAC will be discontinued in early 2018</li>';
				echo '<li>Parallel operation of AKsearch and OPAC until the end of 2017</li>';
				echo '</ul>';
				echo '</div>';
				echo '<div class="akClearer"></div>';
				echo '</div>';
				
				echo '</div>';
					
				echo '<hr/>';
			}
		}
	?>
	</div>
	
	
    <footer role="contentinfo" class="hidden-print">
      <div class="container">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy ?>
      </div>
    </footer>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="modalTitle" class="modal-title"></h4>
          </div>
          <div class="modal-body"><?=$this->transEsc('Loading') ?>...</div>
        </div>
      </div>
    </div>
    <?=$this->googleanalytics()?>
    <?=$this->piwik()?>
    
    
	<?php
	
		/*
		if ($this->layout()->templateDir == 'search' && $this->layout()->templateName == 'home') {
			echo '<div class="akFeatureIntro">';
			
			//echo '<div id="akFeatureIntroHeader" class="akFeatureIntroHideRight">AKsearch</div>';
			echo '<div id="akFeatureIntroSubHeader" class="akFeatureIntroHideRight">Features: neue Suchmaschine der AK Bibliothek Wien</div>';
			
			
			echo '<div id="akFeatureIntroContentBox1" class="akFeatureIntroHideLeft akFeatureIntroContentBox">';
				echo '<div class="akFeatureIntroContentBoxHeader akTextAlignRight">';
          			echo 'Moderne Suchoberfläche <i class="fa fa-chevron-down" aria-hidden="true"></i>';
          		echo '</div>';
				echo '<div class="akFeatureIntroContentBoxText akRight">';
					echo '<ul>';
					echo '<li>Zeitgemäßes Layout</li>';
					echo '<li>Auf mobilen Endgeräten verwendbar</li>';
					echo '<li>Erhöhte Benutzerfreundlichkeit</li>';
					echo '<li><a href="https://github.com/AKBibliothekWien/aksearch" target="_blank">Open Source Software</a></li>';
					echo '</ul>';
    			echo '</div>';
      		echo '</div>';
      		
      		echo '<div id="akFeatureIntroContentBox2" class="akFeatureIntroHideRight akFeatureIntroContentBox">';
	      		echo '<div class="akFeatureIntroContentBoxHeader">';
            		echo '<i class="fa fa-chevron-down" aria-hidden="true"></i> Erweiterte Suchmöglichkeiten';
            	echo '</div>';
	      		echo '<div class="akFeatureIntroContentBoxText">';
		      		echo '<ul>';
		      		echo '<li>Filter zum Einschränken Ihrer Suchergebnisse</li>';
		      		echo '<li><a href="'.$this->url('help-home').'?topic=search" title="'.$this->transEsc('Search Tips').'" class="help-link">Zusätzliche Suchoperatoren</a> für zielgerichtetes Suchen</li>';
		      		echo '<li><a href="/Browse/Home">Stöbern in unserem Bestand</a> nach verschiedenen Gesichtspunkten</li>';
		      		echo '<li>Anzeigen unserer <a href="/Search/NewItem">Neuerwerbungen</a></li>';
		      		echo '</ul>';
	      		echo '</div>';
      		echo '</div>';
      		
      		echo '<div id="akFeatureIntroContentBox3" class="akFeatureIntroHideLeft akFeatureIntroContentBox">';
	      		echo '<div class="akFeatureIntroContentBoxHeader akTextAlignRight">';
	      			echo 'Mehrere Quellen durchsuchen <i class="fa fa-chevron-down" aria-hidden="true"></i>';
	      		echo '</div>';
	      		echo '<div class="akFeatureIntroContentBoxText akRight">';
	      			echo '<p style="text-align: right;">Duchsuchen Sie neben unserem Bibliotheksbestand zusätzliche Quellen.<br />Sie finden sogar unselbständig erschienene Texte (einzelne Zeitschriftenartikel und Buchkapitel).</p>';
		      		echo '<ul class="akRight">';
		      		echo '<li>Komplettes <a href="http://www.ssoar.info/" target="_blank">SSOAR</a> (Social Science Open Access Repository)</a></li>';
		      		echo '<li>Themenrelevante Inhalte des von <a href="https://doaj.org/" target="_blank">DOAJ</a> (Directory of Open Access Journals)</li>';
		      		echo '<li><a href="https://emedien.arbeiterkammer.at/" target="_blank">eMedien der AK Wien</a></li>';
		      		echo '<li>Weitere Quellen werden folgen ...</li>';
		      		echo '</ul>';
	      		echo '</div>';
      		echo '</div>';
      		
      		echo '<div id="akFeatureIntroContentBox4" class="akFeatureIntroHideRight akFeatureIntroContentBox">';
	      		echo '<div class="akFeatureIntroContentBoxHeader">';
	      			echo '<i class="fa fa-chevron-down" aria-hidden="true"></i> Ersatz für alten Katalog';
	      		echo '</div>';
	      		echo '<div class="akFeatureIntroContentBoxText">';
		      		echo '<ul>';
		      		echo '<li>AKsearch ersetzt unseren alten <a href="https://aleph22-prod-sh2.obvsg.at/F?func=find-b-0&CON_LNG=ger&local_base=akw01" target="_blank">Katalog (OPAC)</a></li>';
		      		echo '<li>Ab Anfang 2018 wird der OPAC durch einen Softwareumstieg abgestellt</li>';
		      		echo '<li>Paralellbetrieb von AKsearch und OPAC bis Ende 2017</li>';
		      		echo '</ul>';
	      		echo '</div>';
      		echo '</div>';
				
			echo '</div>';
		}
		*/
	?>
    
  </body>
</html>
