<?
// Set page title.
$this->headTitle($this->translate('Details') . ': ' . $this->driver->getBreadcrumb());

// Grab clean ISBN for convenience:
$isbn = $this->driver->getCleanISBN();
?>
<h3><?=$this->transEsc('detailsTabHeading')?></h3><br />
<table class="table" summary="<?=$this->transEsc('Details')?>">

  <? $summ = $this->driver->getSummary(); if (!empty($summ)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Summary')?>: </th>
		<td>
        <? foreach ($summ as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>


<? $furtherTitles = $this->driver->getFurtherTitles(); if (!empty($furtherTitles)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('furtherTitles')?>: </th>
		<td>
        <? foreach ($furtherTitles as $furtherTitle): ?>
          <?=$this->escapeHtml(str_replace(array('<', '>'), '', $furtherTitle))?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>
  
  <?php
		// Publication type and format
		$publicationType = $this->driver->tryMethod('getPublicationTypeFromIndex');
		$formats = $this->driver->getFormats();
		if ((isset($formats) && ! empty($formats)) || (isset($publicationType) && ! empty($publicationType))) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('Publication Type') . ': </th>';
			echo '<td>';
			if (isset($publicationType) && ! empty($publicationType)) {
				echo $this->transEsc($publicationType);
				if (! empty($formats)) {
					echo ', ' . $this->record($this->driver)->getFormatList();
				}
			}
			echo '</td>';
			echo '</tr>';
		}
		
		$series = $this->driver->getSeries();
		if (isset($series) && !empty($series)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('Series') . ':</th>';
			echo '<td>';
			foreach ($series as $field) {
				/*
				 * Depending on the record driver, $field may either be an array with
				 * "name" and "number" keys or a flat string containing only the series
				 * name. We should account for both cases to maximize compatibility.
				 */
				if (is_array($field)) {
					if (!empty($field['name'])) {
						echo '<a href="' . $this->record($this->driver)->getLink('series', $field['name']) . '">' . $this->escapeHtml(str_replace(array("<", ">"), "", $field['name'])) . '</a>';
						if (!empty($field['number'])) {
							echo ' ' . $this->escapeHtml($field['number']);
						}
						echo '<br />';
					}
				} else {
					echo '<a href="' . $this->record($this->driver)->getLink('series', $field) . '">' . $this->escapeHtml(str_replace(array("<", ">"), "", $field)) . '</a><br />';
				}
			}
			echo '</td>';
			echo '</tr>';
		}
		
		// Subseries
		$subSeries = $this->driver->tryMethod('getSubseries');
		if (isset($subSeries) && !empty($subSeries)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('subseries') . ': </th>';
			echo '<td>';
			foreach ($subSeries as $subSer) {
				echo $this->escapeHtml(str_replace(array('<', '>'), '', $subSer)) . '<br />';
			}
			echo '</td>';
			echo '</tr>';
		}
		
		// Content summaries
		$contentSummaries = $this->driver->tryMethod('getContentSummary');
		if (isset($contentSummaries) && !empty($contentSummaries)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('ContentSummary') . ': </th>';
			echo '<td>';
			foreach ($contentSummaries as $contentSummary) {
				echo '<div class="akTableInnerRow">';
				if ($contentSummary != null && !empty($contentSummary)) {
					echo $this->escapeHtml($contentSummary);
				}
				echo '</div>';
			}
			echo '</td>';
			echo '</tr>';
		}
		
		// Abstracts
		$abstracts = $this->driver->tryMethod('getAbstract');
		if (isset($abstracts) && !empty($abstracts)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('Abstract') . ': </th>';
			echo '<td>';
			foreach ($abstracts as $abstract) {
				echo '<div class="akTableInnerRow">';
				if ($abstract!= null && !empty($abstract)) {
					echo $this->escapeHtml($abstract);
				}
				echo '</div>';
			}
			echo '</td>';
			echo '</tr>';
		}
		
		// Attachments
		$attachments = $this->driver->tryMethod('getAttachments');
		if (isset($attachments) && !empty($attachments)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('attachment') . ': </th>';
			echo '<td>';
			foreach ($attachments as $attachment) {
				$attachmentTitle = str_replace(array('<', '>'), '', $attachment['title']);
				$attachmentType = '';
				// $attachmentType = ($attachment['type'] != 'NoAttachmentType') ? preg_replace('/\s*-+>/', '', $attachment['type']).': ' : null;
				$attachmentSys = ($attachment['solrId'] != 'NoAttachmentSys') ? $attachment['solrId'] : null;
				
				if ($attachmentSys != null) {
					echo '<a href="' . $this->recordLink()->getUrl() . $attachmentSys . '">' . $attachmentType . $this->escapeHtml($attachmentTitle) . '</a><br/>';
				} else {
					echo $attachmentType . $this->escapeHtml($attachmentTitle) . '<br/>';
				}
			}
			echo '</td>';
			echo '</tr>';
		}
		
		// Attachment to
		$attachmentsTo = $this->driver->tryMethod('getAttachmentsTo');
		if (isset($attachmentsTo) && !empty($attachmentsTo)) {
			$contentDisplayed = true;
			
			echo '<tr>';
			echo '<th>' . $this->transEsc('attachmentTo') . ': </th>';
			echo '<td>';
			foreach ($attachmentsTo as $attachmentTo) {
				$attachmentToTitle = str_replace(array('<', '>'), '', $attachmentTo['title']);
				$attachmentToType = ($attachmentTo['type'] != 'NoAttachmentToType' && preg_match('/^Beil. zu\s*$/', $attachmentTo['type']) != 1) ? preg_replace('/\s*-+>/', '', trim($attachmentTo['type'])) . ': ' : null;
				$attachmentToSys = ($attachmentTo['solrId'] != 'NoAttachmentToSys') ? $attachmentTo['solrId'] : null;
				if ($attachmentToSys != null) {
					echo '<a href="' . $this->recordLink()->getUrl() . $attachmentToSys . '">' . $attachmentToType . $this->escapeHtml($attachmentToTitle) . '</a><br/>';
				} else {
					echo $attachmentToType . $this->escapeHtml($attachmentToTitle) . '<br/>';
				}
			}
			echo '</td>';
			echo '</tr>';
		}
		
		// Other relation
		$predecessors = $this->driver->tryMethod('getOtherRelations');
		if (isset($predecessors) && !empty($predecessors)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('otherRelation') . ': </th>';
			echo '<td>';
			foreach ($predecessors as $otherRelation) {
				$otherRelationTitle = str_replace(array('<<', '>>'), '', trim($otherRelation['title']));
				$otherRelationType = ($otherRelation['type'] != 'NoRelationNote') ? trim($otherRelation['type']) . ': ' : null;
				$otherRelationComment = ($otherRelation['comment'] != 'NoComment') ? trim($otherRelation['comment']) : null;
				$otherRelationSys = ($otherRelation['solrId'] != 'NoOtherRelationId') ? $otherRelation['solrId'] : null;
				echo '<div class="akTableInnerRow">';
				echo $this->escapeHtml($otherRelationType);
				if ($otherRelationSys!= null) {
					echo '<a href="' . $this->recordLink()->getUrl() . $otherRelationSys. '">' . $this->escapeHtml($otherRelationTitle) . '</a>';
				} else {
					echo $this->escapeHtml($otherRelationTitle);
				}
				echo  ($otherRelationComment != null ? ' ('.$this->escapeHtml($otherRelationComment).')' : '');
				echo '</div>';
			}
			echo '</td>';
			echo '</tr>';
		}
		
		// Physical description
		$physical = $this->driver->getPhysicalDescriptions();
		if (! empty($physical)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('Physical Description') . ': </th>';
			echo '<td>';
			foreach ($physical as $field) {
				echo $this->escapeHtml($field) . '<br/>';
			}
			echo '</td>';
			echo '</tr>';
		}
		
		// Publication frequency
		$freq = $this->driver->getPublicationFrequency();
		if (! empty($freq)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('Publication Frequency') . ': </th>';
			echo '<td>';
			echo $this->escapeHtml($freq);
			echo '</td>';
			echo '</tr>';
		}
			
		// Notes
		$notes = $this->driver->tryMethod('getNotes');
		if (isset($notes) && ! empty($notes)) {
			$contentDisplayed = true;
			echo '<tr>';
			echo '<th>' . $this->transEsc('Notes') . ':</th>';
			echo '<td>';
			foreach ($notes as $note) {
				echo $this->escapeHtml($note) . '<br />';
			}
			echo '</td>';
			echo '</tr>';
		}
		?>

  

  <? $playTime = $this->driver->getPlayingTimes(); if (!empty($playTime)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Playing Time')?>: </th>
		<td>
        <? foreach ($playTime as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $system = $this->driver->getSystemDetails(); if (!empty($system)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Format')?>: </th>
		<td>
        <? foreach ($system as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $audience = $this->driver->getTargetAudienceNotes(); if (!empty($audience)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Audience')?>: </th>
		<td>
        <? foreach ($audience as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $awards = $this->driver->getAwards(); if (!empty($awards)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Awards')?>: </th>
		<td>
        <? foreach ($awards as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $credits = $this->driver->getProductionCredits(); if (!empty($credits)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Production Credits')?>: </th>
		<td>
        <? foreach ($credits as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $bib = $this->driver->getBibliographyNotes(); if (!empty($bib)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Bibliography')?>: </th>
		<td>
        <? foreach ($bib as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('ISBN')?>: </th>
		<td>
        <? foreach ($isbns as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>


  <? $doi = $this->driver->tryMethod('getCleanDOI'); if (!empty($doi)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('DOI')?>: </th>
		<td><?=$this->escapeHtml($doi)?></td>
	</tr>
  <? endif; ?>

  <? $related = $this->driver->getRelationshipNotes(); if (!empty($related)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Related Items')?>: </th>
		<td>
        <? foreach ($related as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $access = $this->driver->getAccessRestrictions(); if (!empty($access)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Access')?>: </th>
		<td>
        <? foreach ($access as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $findingAids = $this->driver->getFindingAids(); if (!empty($findingAids)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Finding Aid')?>: </th>
		<td>
        <? foreach ($findingAids as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $publicationPlaces = $this->driver->getHierarchicalPlaceNames(); if (!empty($publicationPlaces)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Publication_Place')?>: </th>
		<td>
        <? foreach ($publicationPlaces as $field): ?>
          <?=$this->escapeHtml($field)?><br />
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? $authorNotes = empty($isbn) ? array() : $this->authorNotes($isbn); if (!empty($authorNotes)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
		<th><?=$this->transEsc('Author Notes')?>: </th>
		<td>
        <? foreach ($authorNotes as $provider => $list): ?>
          <? foreach ($list as $field): ?>
            <?=$field['Content']?><br />
          <? endforeach; ?>
        <? endforeach; ?>
      </td>
	</tr>
  <? endif; ?>

  <? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
    <tr>
		<td colspan="2"><?=$this->transEsc('no_description')?></td>
	</tr>
  <? endif; ?>
</table>
