sudo: required
language: php
php:
  - 5.4

env:
  - VUFIND_HOME=$PWD VUFIND_LOCAL_DIR=$PWD/local

before_script:
  - wget https://github.com/pear/Console_Getopt/archive/v1.4.1.tar.gz 
  - tar xvzf v1.4.1.tar.gz 
  - cd Console_Getopt-1.4.1/ 
  - pear install package.xml
  - pear install channel://pear.horde.org/Horde_Role
  - pear install pear/PHP_CodeSniffer
  - pear channel-discover pear.phing.info
  - pear clear-cache
  - pear install phing/phing
  - composer global require fabpot/php-cs-fixer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv rehash

script:
  - phpunit --stderr --configuration module/VuFind/tests/phpunit.xml
  - phpcs --standard=PEAR --ignore=*/config/*,*/tests/* --extensions=php $PWD/module
  - phing php-cs-fixer-dryrun
