<? if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>

  <div class="row">
    <fieldset class="col-sm-12">
      <legend><?=$this->transEsc('Limit To')?></legend>
      <? if (!empty($this->checkboxFacets)): ?>
        <?=$this->render('search/advanced/checkbox-filters.phtml')?>
      <? endif; ?>
      <div class="row">
      
      <!--
      <div class="col-sm-4">
      	<select class="form-control" id="limit_akcustom" name="filter[]" multiple="multiple" size="10">
      		<option value="~locationCode_str:ZSF">ZSF</option>
      		<option value="~customField_txt_mv:'Digitaler Wandel'">DW</option>
      	</select>
      </div>
      -->
      
        <? foreach ($this->facetList as $field => $list): ?>
        
        <?php 
        // Check for AK sorting
        $label = $list['label'];
        $aksort = false;
        if (preg_match('/\[aksort\]/',$label)) {
        	$aksort = true;
        	$label = preg_replace('/\[aksort\]/', "", $label);
        }
        
        
        // Check for AK custom advanced facets
        $akCustomAdvFacets = false;
        ?>
        
          <div class="col-sm-<?=floor(12/count($this->facetList)) ?>">
            <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>"><?=$this->transEsc($label)?>:</label>
            
            <select class="form-control" id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>" name="filter[]" multiple="multiple" size="10">
              <? if (is_array($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
                <? foreach ($list['list'] as $value): ?>
                  <? $display = str_pad('', 4 * $value['level'] * 6, '&nbsp;', STR_PAD_LEFT) . $this->escapeHtml($value['displayText']); ?>
                  <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$display?></option>
                <? endforeach; ?>
              <? else: ?>

                <?
                $sorted = array();
                if ($aksort) {
	                $sortBy = array();
	                foreach ($list['list'] as $i => $value) {
	                	if (!empty($value['displayText'])) {
	                		$sortText = preg_replace("/^(([<!][^a-zA-Z0-9]+).*?[>!]+[\s\W_]*)|[<>]/", "", $value['displayText']);
	                		$sorted[$i]['displayText'] = $this->transEsc(str_replace(array("<", ">"), "", $value['displayText']));
	                		$sorted[$i]['sortText'] = $sortText;
	                		$sorted[$i]['key'] = $i;
	                		$sortBy[] = $sortText;
	                	}
	                }
	                array_multisort($sortBy, SORT_LOCALE_STRING, $sorted);
                } else {
	                // Sort the current facet list alphabetically; we'll use this data
	                // along with the foreach below to display facet options in the
	                // correct order.
	                foreach ($list['list'] as $i => $value) {
	                  if (!empty($value['displayText'])) {
	                    
	                    if (!array_key_exists('akCustomAdvancedFacetField', $value)) {
	                    	// Default
	                    	$sorted[$i] = $this->transEsc(str_replace(array("<", ">"), "", $value['displayText']));
	                    } else {
	                    	// AK custom advanced facets
	                    	$akCustomAdvFacets = true;
	                    	$sorted[$i]['displayText'] = $this->transEsc(str_replace(array("<", ">"), "", $value['displayText']));
	                    	$sorted[$i]['akCustomAdvancedFacetField'] = $value['akCustomAdvancedFacetField'];
	                    }
	                  }
	                }
	                natcasesort($sorted);
                }
                ?>
                <? foreach ($sorted as $i => $display): ?>
                  <?php 
                  $displayText = '';
                  if ($aksort) {
                  	$value = $list['list'][$display['key']];
                  	$displayText = $display['displayText'];
                  } else if ($akCustomAdvFacets) {
                  	$value = $list['list'][$i];
                  	$displayText = $display['displayText'];
                  	$field = $display['akCustomAdvancedFacetField'];
                  } else {
                  	$value = $list['list'][$i];
                  	$displayText = $display;
                  }
                  ?>
                  
                  <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?> title="<?=$this->escapeHtml($this->transEsc($displayText))?>"><?=$this->escapeHtml($this->transEsc($displayText))?></option>
                <? endforeach; ?>

              <? endif; ?>

            </select>
            
          </div>
        <? endforeach; ?>
      </div>
    </fieldset>
  </div>
<? endif; ?>
<div class="row">
  <? if (isset($this->illustratedLimit)): ?>
    <fieldset class="col-sm-4">
      <legend><?=$this->transEsc("Illustrated")?>:</legend>
      <? foreach ($this->illustratedLimit as $current): ?>
        <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected']?' checked="checked"':''?>/>
        <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br/>
      <? endforeach; ?>
    </fieldset>
  <? endif; ?>
  <?=$this->render('search/advanced/limit.phtml')?>
  <?=$this->render('search/advanced/ranges.phtml')?>
</div>