<?
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Only display home library form if we have multiple pickup locations:
    $showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Your Profile')?></h2>
    <?=$this->flashmessages();?>

    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $this->auth()->isLoggedIn())); ?>

    <table class="table table-striped">
      <?
        echo $this->renderArray(
          $arrTemplate, $this->profile,
          array(
            $this->transEsc('First Name') => 'firstname',
            $this->transEsc('Last Name') => 'lastname'
          )
        );
       ?>
      <? if ($showHomeLibForm): ?>
        <tr><th><?=$this->transEsc('Preferred Library')?>:</th>
        <?
          $selected = (isset($this->profile['home_library']) && $this->profile['home_library'] != "")
              ? $this->profile['home_library'] : $this->defaultPickupLocation
        ?>
        <td>
          <form id="profile_form" class="form-inline" method="post">
            <select id="home_library" name="home_library" class="form-control">
              <? foreach ($this->pickup as $lib): ?>
                <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->escapeHtml($lib['locationDisplay'])?></option>
              <? endforeach; ?>
            </select>
            <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Save')?>" />
          </form>
        </td>
      <? endif; ?>
      <?
      	$rowsArray = [];      	
      	(isset($this->profile['address1']) && !empty($this->profile['address1'])) ? $rowsArray[$this->transEsc('Address') . ' 1'] = 'address1' : null;
      	(isset($this->profile['address2']) && !empty($this->profile['address2'])) ? $rowsArray[$this->transEsc('Address') . ' 2'] = 'address2' : null;
      	(isset($this->profile['address3']) && !empty($this->profile['address3'])) ? $rowsArray[$this->transEsc('Address') . ' 3'] = 'address3' : null;
      	(isset($this->profile['address4']) && !empty($this->profile['address4'])) ? $rowsArray[$this->transEsc('Address') . ' 4'] = 'address4' : null;
      	(isset($this->profile['address5']) && !empty($this->profile['address5'])) ? $rowsArray[$this->transEsc('Address') . ' 5'] = 'address5' : null;
      	(isset($this->profile['zip']) && !empty($this->profile['zip'])) ? $rowsArray[$this->transEsc('Zip')] = 'zip' : null;
      	(isset($this->profile['city']) && !empty($this->profile['city'])) ? $rowsArray[$this->transEsc('City')] = 'city' : null;
      	(isset($this->profile['country']) && !empty($this->profile['country'])) ? $rowsArray[$this->transEsc('Country')] = 'country' : null;
      	(isset($this->profile['phone']) && !empty($this->profile['phone'])) ? $rowsArray[$this->transEsc('Phone Number')] = 'phone' : null;
      	(isset($this->profile['phone2']) && !empty($this->profile['phone2'])) ? $rowsArray[$this->transEsc('Phone Number') . ' 2'] = 'phone2' : null;
      	(isset($this->profile['email']) && !empty($this->profile['email'])) ? $rowsArray[$this->transEsc('email')] = 'email' : null;
      	if (isset($this->profile['emailsAdditional'])) {
      		foreach($this->profile['emailsAdditional'] as $emailAdditional) {
      			(isset($emailAdditional) && !empty($emailAdditional)) ? $rowsArray[$this->transEsc('email')] = $emailAdditional : null;
      		}
      	}
      	(isset($this->profile['group']) && !empty($this->profile['group'])) ? $rowsArray[$this->transEsc('Group')] = 'group' : null;
      	
      	// Render the array as table rows (see $arrTemplate above):
        echo $this->renderArray($arrTemplate, $this->profile, $rowsArray);
      ?>
    </table>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'profile'))?>
  </div>
</div>