<?
  if($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
  } else {
    $user_id = false;
  }
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core"); 
     $cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <div class="col-sm-9">
  <? else: ?>
  <div class="col-sm-12">
  <? endif; ?>

	<?php
	$mainTitle = $this->escapeHtml(str_replace(array("<", ">"), "", $this->driver->getShortTitle()));
	$subTitle = $this->escapeHtml(str_replace(array("<", ">"), "", ucfirst($this->driver->getSubtitle())) . ' ' . str_replace(array("<", ">"), "", $this->driver->getTitleSection()));
    echo "<h3>".$mainTitle."</h3>";
    echo "<h4>".$subTitle."</h4>";
    ?>
    
    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Published in')?>:</th>
        <td>
          <? $containerID = $this->driver->getContainerRecordID(); ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("VuFind|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
      

    <!-- Print the type of the publication (if it's a journal, multi-volume-work, monograph, etc.) -->
    <? $publicationType = $this->driver->tryMethod('getPublicationTypeFromIndex') ?>
    <? if ($publicationType != null): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Publication Type')?>:</th>
      <td>
      	<?=$this->escapeHtml($publicationType)?>
      </td>
    </tr>
    <? endif; ?>
    
    
    <!-- If it's an article or essay which is contained in another work (journal or book): -->
    <?php   
    $isArticle = $this->driver->tryMethod('isArticle');
    $isChildVolume = $this->driver->tryMethod('isChildVolume');
    
    if (isset($isArticle) && $isArticle == true) { // It's an article (Unselbstständig)
    	$arrArticleParentSYSs = $this->driver->tryMethod('getParentSYSs');
    	$articleParentSYS = (isset($arrArticleParentSYSs)) ? $arrArticleParentSYSs[0] : null; // There should only be 1 parentSYS for an article
	    $articleParentTitle = $this->driver->tryMethod('getArticleParentTitle');
	    
	    if ($articleParentTitle != null) {
	    	$articleParentTitle = str_replace(array("<", ">"), "", $articleParentTitle);
	    	echo '<tr valign="top">';
		    	echo'<th>'.$this->transEsc('Published in').'</th>';
		 		echo '<td>';
		 			if ($articleParentSYS != null) {
		    			echo '<a href="'.$this->recordLink()->getUrl().$articleParentSYS.'/Holdings">'.$this->escapeHtml($articleParentTitle).'</a><br/>';
		 			} else {
		 				echo '<a href="'.$this->record($this->driver)->getLink('title', $articleParentTitle).'">'.$this->escapeHtml($articleParentTitle).'</a><br/>';
		 			}
		    		
		    	echo '</td>';
	    	echo '</tr>';
	    }
    } else if (isset($isChildVolume) && $isChildVolume == true) { // It's a "normal" child volume
		if ($this->driver->tryMethod('getParentSYSs') != null) {
			echo '<tr valign="top">';
				echo '<th>'.$this->transEsc('parentRecord').'</th>';
				echo '<td>';
					$parentRecordSYSs = $this->driver->tryMethod('getParentSYSs');
					$parentRecordTitles = $this->driver->tryMethod('getParentTitles');
					foreach ($parentRecordSYSs as $key => $value) {
						$parentRecordTitle = str_replace(array("<", ">"), "", $parentRecordTitles[$key]);
						echo '<a href="'.$this->recordLink()->getUrl().$value.'/MultiVolumeWorks">'.$this->escapeHtml($parentRecordTitle).'</a><br/>';
					}
				echo '</td>';
			echo '</tr>';
		}
    }
    
    ?>
      
      <? $authors = $this->driver->getAuthors(); if (!empty($authors)): ?>
      <tr>
      	<th><?=$this->transEsc('Authors')?>: </th>
      	<td>
      	 <? foreach($authors as $author): ?>
            <a property="author" href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a><br/>
         <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
      
	 <? $corporateAuthors = $this->driver->getCorporateAuthors(); if (!empty($corporateAuthors)): ?>
      <tr>
      	<th><?=$this->transEsc('Corporate Author')?>: </th>
      	<td>
      	 <? foreach($corporateAuthors as $corporateAuthor): ?>
         	<a property="creator" href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($corporateAuthor)?>&type=AllFields&limit=20"><?=$this->escapeHtml($corporateAuthor)?></a><br />
         <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
      

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($this->transEsc($lang))?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>
            
      <? $pubNames = $this->driver->getPublisherNames(); if (!empty($pubNames)): ?>
      <tr>
      	<th><?=$this->transEsc('Publisher')?>: </th>
      	<td>
      	 <? foreach($pubNames as $pubName): ?>
            <span property="name"><?=$this->escapeHtml($pubName)?></span><br/>
         <? endforeach; ?>
        </td>
        
      </tr>
      <? endif; ?>
        
      <? $pubPlace = $this->driver->getPublicationPlace(); if (!empty($pubPlace)): ?>
      <tr>
      	<th><?=$this->transEsc('place')?>: </th>
      	<td><span property="publicationPlace"><?=$this->escapeHtml($pubPlace)?></span></td>
      </tr>
      <? endif; ?>
      
      <? $pubHistory = $this->driver->getPublicationHistory(); if (!empty($pubHistory)): ?>
      <tr>
      	<th><?=$this->transEsc('publicationHistory')?>: </th>
      	<td><span property="publicationHistory"><?=$this->escapeHtml($pubHistory)?></span></td>
      </tr>
      <? endif; ?>
      
      <? $pubDate = $this->driver->getPublishDate(); if (!empty($pubDate)): ?>
      <tr>
      	<th><?=$this->transEsc('Year of Publication')?>: </th>
      	<td><span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span></td>
      </tr>
      <? endif; ?>
      
      
      
      <? $pubFrequency = $this->driver->getFrequencyOfPublication(); if (!empty($pubFrequency)): ?>
      <tr>
      	<th><?=$this->transEsc('frequencyOfPublication')?>: </th>
      	<td><span property="publicationFrequency"><?=$this->escapeHtml($pubFrequency)?></span></td>
      </tr>
      <? endif; ?>     

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subjectLine" property="keywords">
            <? $subject = ''; ?>
            <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow"><?=trim($this->escapeHtml($subfield))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(null, null, 'count', $user_id); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <a id="tagRecord" class="btn btn-link modal-link pull-right flip" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>">
              <i class="fa fa-plus"></i> <?=$this->transEsc('Add Tag')?></a>
            </a>
            <?=$this->context($this)->renderInContext('record/taglist', array('tagList'=>$tagList, 'loggedin'=>$loggedin)) ?>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
