<?

  if($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
  } else {
    $user_id = false;
  }


  // Test entity facts via PHP
  //$this->driver->getEntityFact('118540238');
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     //$cover = $this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large')); // Cover with link
     $cover = $this->record($this->driver)->getCover('core', 'medium', false); // Cover without link
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <div class="col-sm-9">
  <? else: ?>
  <div class="col-sm-12">
  <? endif; ?>

	<?php
	$mainTitle = trim(str_replace(array('&lt;', '&gt;'), '', $this->record($this->driver)->getTitleHtml()));
	$subseriesTitle = ($this->driver->tryMethod('getSubseries')) ? $this->escapeHtml(str_replace(array('<', '>'), '', implode(', ', $this->driver->tryMethod('getSubseries')))) : null;
	$subTitle = $this->escapeHtml(str_replace(array('<', '>'), '', ucfirst($this->driver->getSubtitle())) . ' ' . str_replace(array('<', '>'), '', $this->driver->getTitleSection()));
	$volumeNo = trim($this->escapeHtml($this->driver->getVolumeNo()));

	// Title
	echo '<h1 class="akH1">';
    	echo $mainTitle;
    	if (isset($subseriesTitle) && !empty($subseriesTitle)) {
    		echo ': '.$subseriesTitle;
    	}
    echo '</h1>';

    // Subtitle
    echo '<h2 class="akH2">'.$subTitle.'</h2>';
    if ($volumeNo != null) {
    	echo '<h2 class="akH2">'.$this->transEsc('volume').': '.$volumeNo.'</h2>';
    }
    ?>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>
      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">


    <!-- If it's an article or essay which is contained in another work (journal or book): -->
    <?php
    $isArticle = $this->driver->tryMethod('isArticle');
    $isChildVolume = $this->driver->tryMethod('isChildVolume');

    if (isset($isArticle) && $isArticle == true) { // It's an article (Unselbstständig)

    	$arrArticleParentSYSs = $this->driver->tryMethod('getParentSYSs');
    	$articleParentSYS = (isset($arrArticleParentSYSs)) ? $arrArticleParentSYSs[0] : null; // There should only be 1 parentSYS for an article
	    $articleParentTitle = $this->driver->tryMethod('getArticleParentTitle');

	    if ($articleParentTitle != null) {
	    	$articleParentTitle = str_replace(array('<', '>'), '', $articleParentTitle);
	    	echo '<tr valign="top">';
		    	echo'<th>'.$this->transEsc('Published in').':</th>';
		 		echo '<td>';
		 			if ($articleParentSYS != null) {
		    			//echo '<a href="'.$this->recordLink()->getUrl().$articleParentSYS.'/Holdings#journalholding">'.$this->escapeHtml($articleParentTitle).'</a><br/>';
		 				echo '<a href="'.$this->recordLink()->getUrl().$articleParentSYS.'">'.$this->escapeHtml($articleParentTitle).'</a><br/>';
		 			} else {
		 				echo '<a href="'.$this->record($this->driver)->getLink('title', $articleParentTitle).'">'.$this->escapeHtml($articleParentTitle).'</a><br/>';
		 			}

		    	echo '</td>';
	    	echo '</tr>';
	    }
    } else if (isset($isChildVolume) && $isChildVolume == true) { // It's a "normal" child volume
		if ($this->driver->tryMethod('getParentSYSs') != null) { // Show parent volume with direct link to record, or ...
			echo '<tr valign="top">';
				echo '<th>'.$this->transEsc('parentRecord').':</th>';
				echo '<td>';
					$parentRecordSYSs = $this->driver->tryMethod('getParentSYSs');
					$parentRecordTitles = $this->driver->tryMethod('getParentTitles');
					foreach ($parentRecordSYSs as $key => $value) {
						$parentRecordTitle = str_replace(array('<', '>'), '', $parentRecordTitles[$key]);
						echo '<a href="'.$this->recordLink()->getUrl(null).$value.'/MultiVolumeWorks">'.$this->escapeHtml($parentRecordTitle).'</a><br/>';
						//echo '<a href="'.$this->recordLink()->getUrl($this->driver).$value.'/MultiVolumeWorks">'.$this->escapeHtml($parentRecordTitle).'</a><br/>';
					}
				echo '</td>';
			echo '</tr>';
		} else { // ... show Series with a search link.
			$series = $this->driver->getSeries();
			if (!empty($series)) {
				echo '<tr valign="top">';
				echo '<th>'.$this->transEsc('Series').':</th>';
				foreach ($series as $field) {
					/* Depending on the record driver, $field may either be an array with
					 "name" and "number" keys or a flat string containing only the series
					 name.  We should account for both cases to maximize compatibility. */
					echo '<td>';
					if (is_array($field)) {
						if (!empty($field['name'])) {
							echo '<a href="'.$this->record($this->driver)->getLink('series', $field['name']).'">'.$this->escapeHtml(str_replace(array('<', '>'), '', $field['name'])).'</a>';
							if (!empty($field['number'])) {
								echo ' '.$this->escapeHtml($field['number']);
							}
							echo '<br />';
						}
					} else {
						echo '<a href="'.$this->record($this->driver)->getLink('series', $field).'">'.$this->escapeHtml(str_replace(array('<', '>'), '', $field)).'</a><br />';
					}
					echo '</td>';
				}
				echo '</tr>';
			}
		}
    }
    ?>

    <!-- // PARTICIPANTS (with role and authority info) -->
    <?php
      /*
      // ORIGINAL
      <? $authors = $this->driver->getAuthors(); if (!empty($authors)): ?>
      <tr>
      	<th><?=$this->transEsc('Authors')?>: </th>
      	<td>
      	 <? foreach($authors as $author): ?>
            <a property="author" href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml(str_replace(array('<', '>'), '', $author))?></a><br/>
         <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
      */

		$participants = $this->driver->getParticipants();
		if (isset($participants) && !empty($participants)) {

			// 'NoRole' is normally the same as 'Author' or 'VerfasserIn'. So if we have a record with persons that do have a role 'Author' and
			// also persons that do not have a role (which gives us 'NoRole'), then we have to put 'NoRole' and 'Author' togehter into one row.
			// Example: 000459783 / AC13391021
			$participantsNoRole = [];
			$participantsTranslated = [];
			foreach ($participants as $role => $participant) {
				if ($role == 'NoRole') {
					$participantsNoRole[$this->transEsc($role)] = $participant;
				} else {
					$participantsTranslated[$role] = $participant;
				}
			}
			$participants = array_merge_recursive($participantsNoRole, $participantsTranslated);

			foreach ($participants as $role => $participant) {
                            echo '<tr>';
                                echo '<th>'.$this->transEsc($role).':</th>';
                                echo '<td>';
                                    foreach ($participant as $key => $gndName) {
                                        $gnd = key($gndName);
                                        $name = $gndName[key($gndName)];
                                        echo '<a property="author" href="'.$this->record($this->driver)->getLink('author', $name).'">';
                                            echo $this->escapeHtml(str_replace(array('<', '>'), '', $name));
                                        echo '</a>';

                                        // Entity Facts via PHP curl (Zend Http Object)
                                        // See also AkSearch\Controller\AkAjaxController and aksearch.js in folder "themes/aksearch/js"
                                        if (isset($gnd) &&
                                            !empty($gnd) &&
                                            $gnd != 'NoGndId' &&
                                            !preg_match('/^BIP/', $gnd) &&
                                            !preg_match('/PND$/', $gnd) &&
                                            !preg_match('/^BIK/', $gnd) &&
                                            !preg_match('/GKD$/', $gnd)
                                            ) {
                                            echo '&nbsp;&nbsp;<span class="akEntityFactsOpener" data-gndid="'.preg_replace('/\(.*?\)/', '', $gnd).'"><i class="fa fa-info-circle akEntityFactsInfo" aria-hidden="true"></i></span>';
                                            }
                                        echo '<br/>';
                                    }
                                echo '</td>';
                            echo '</tr>';
			}
		}
		?>


	  <?php
	  $publicationDetails = $this->driver->getPublicationDetails();
	  $publisher = (isset($publicationDetails['publisher']) ? $publicationDetails['publisher'] : "");
	  $publicationPlace = (isset($publicationDetails['publishPlace']) ? $publicationDetails['publishPlace'] : "");
	  $publicationYear = (isset($publicationDetails['publishDate']) ? $publicationDetails['publishDate'] : ""); 
	  $publicationHistory = $this->driver->getPublicationHistory();


	  // Publication date or history
	  if (isset($publicationHistory) && !empty($publicationHistory)) {
	  	echo '<tr>';
	  	echo '<th>'.$this->transEsc('publicationHistory').': </th>';
	  	echo '<td><span property="publicationHistory">'.$this->escapeHtml($publicationHistory).'</span></td>';
	  	echo '</tr>';
	  } else if (!empty($publicationYear)) {
	  	echo '<tr>';
	  	echo '<th>'.$this->transEsc('Year of Publication').': </th>';
	  	echo '<td><span property="publicationDate">'.$this->escapeHtml($publicationYear).'</span></td>';
	  	echo '</tr>';
	  }

	  /*
	  // Publication frequency - Is in "Description" tab!
	  $pubFrequency = $this->driver->getPublicationFrequency();
	  if (isset($pubFrequency) && !empty($pubFrequency)) {
	  	echo '<tr>';
	  	echo '<th>'.$this->transEsc('frequencyOfPublication').': </th>';
	  	echo '<td><span property="publicationFrequency">'.$this->escapeHtml($pubFrequency).'</span></td>';
	  	echo '</tr>';
	  }
	  */

	  // Publisher name and place
	  if (isset($publisher)) {
	  	echo '<tr>';
	  	echo '<th>'.$this->transEsc('Publisher').': </th>';
	  	$publishString = '<span property="name">'.$this->escapeHtml(str_replace(array('<', '>'), '', $publisher)).'</span>';
	  	if (isset($publicationPlace)) {
	  		$publishString .= ' (<span property="publicationPlace">'.$this->escapeHtml($publicationPlace).'</span>)';
	  	}
	  	echo '<td>'.$publishString.'</td>';
	  	echo '</tr>';
	  } else if (isset($publicationPlace)) {
	  	echo '<tr>';
	  	echo '<th>'.$this->transEsc('Publication_Place').': </th>';
	  	echo '<td><span property="publicationPlace">'.$this->escapeHtml($publicationPlace).'</span></td>';
	  	echo '</tr>';
	  }
	  ?>

	  <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml(str_replace(array('<', '>'), '', $edition))?></td>
      </tr>
      <? endif; ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($this->transEsc($lang))?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Published in')?>:</th>
        <td>
          <? $containerID = $this->driver->getContainerRecordID(); ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("VuFind|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>



		<?php

		// Predecessor title
		$predecessors = $this->driver->tryMethod('getPredecessors');
		if (isset($predecessors) && !empty($predecessors)) {
			echo '<tr>';
			echo '<th>' . $this->transEsc('Previous Title') . ': </th>';
			echo '<td>';
			foreach ($predecessors as $predecessor) {
				$predecessorTitle = str_replace(array('<', '>'), '', trim($predecessor['title']));
				$predecessorSys = ($predecessor['solrId'] != 'NoPredecessorId') ? $predecessor['solrId'] : null;
				echo '<div class="akTableInnerRow">';
				if ($predecessorSys != null) {
					echo '<a href="' . $this->recordLink()->getUrl() . $predecessorSys. '">' . $this->escapeHtml($predecessorTitle) . '</a>';
				} else {
					echo $this->escapeHtml($predecessorTitle);
				}
				echo '</div>';
			}
			echo '</td>';
			echo '</tr>';
		}

		// Successor title
		$successors = $this->driver->tryMethod('getSuccessors');
		if (isset($successors) && !empty($successors)) {
			echo '<tr>';
			echo '<th>' . $this->transEsc('New Title') . ': </th>';
			echo '<td>';
			foreach ($successors as $successor) {
				$successorTitle = str_replace(array('<', '>'), '', trim($successor['title']));
				$successorSys = ($successor['solrId'] != 'NoSuccessorId') ? $successor['solrId'] : null;
				echo '<div class="akTableInnerRow">';
				if ($successorSys != null) {
					echo '<a href="' . $this->recordLink()->getUrl() . $successorSys. '">' . $this->escapeHtml($successorTitle) . '</a>';
				} else {
					echo $this->escapeHtml($successorTitle);
				}
				echo '</div>';
			}
			echo '</td>';
			echo '</tr>';
		}

		/*
		// ORIGINAL
      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml(str_replace(array('<', '>'), '', $field))?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml(str_replace(array('<', '>'), '', $field))?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
      */
      ?>



       <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
          <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" target="new"><?=$this->escapeHtml($this->transEsc($current['desc']))?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>


	    <?php
	    /*
	    // Publication type and format - Is in "Description" tab!
	    $publicationType = $this->driver->tryMethod('getPublicationTypeFromIndex');
	    $formats = $this->driver->getFormats();
	    echo '<tr>';
	    echo '<th>'.$this->transEsc('Publication Type').': </th>';
	    echo '<td>';
	    if ($publicationType != null && !empty($publicationType)) {
	    	echo $this->transEsc($publicationType);
	    	if (!empty($formats)) {
	    		echo ', '.$this->record($this->driver)->getFormatList();
	    	}
	    }
	    echo '</td>';
	    echo '</tr>';
	    */

	    // Other editions
	    $attachments = $this->driver->tryMethod('getOtherEditions');
	    if (isset($attachments) && !empty($attachments)) {
	    	echo '<tr>';
	    	echo '<th>'.$this->transEsc('otherEdition').': </th>';
	    	echo '<td>';
	    	foreach ($attachments as $otherEdition) {
	    		$otherEditionTitle = $otherEdition['title'];
	    		$otherEditionType = ($otherEdition['type'] != 'NoOtherEditionType') ? preg_replace('/\s*-+>/', '', $otherEdition['type']).': ' : null;
	    		$otherEditionSys = ($otherEdition['solrId'] != 'NoOtherEditionSys') ? $otherEdition['solrId'] : null;

	    		if ($otherEditionSys != null) {
	    			echo '<a href="'.$this->recordLink()->getUrl().$otherEditionSys.'">'.$otherEditionType.$this->escapeHtml($otherEditionTitle).'</a><br/>';
	    		} else {
	    			echo $otherEditionType.$this->escapeHtml($otherEditionTitle).'<br/>';
	    		}
	    	}
	    	echo '</td>';
	    	echo '</tr>';

	    }

	    /*
	    // ZSL (Zeitschriften-Ablage-Nr.)
	    $zsl = $this->driver->tryMethod('getZsl');
	    if (isset($zsl) && !empty($zsl)) {
	    	echo '<tr>';
	    	echo '<th>'.$this->transEsc('zsl').': </th>';
	    	echo '<td>';
	    	echo implode(', ', $zsl);
	    	echo '</td>';
	    	echo '</tr>';
	    }
	    */

	    // Dewey Decimal Classifications (DDCs)
	    $ddcs = $this->driver->tryMethod('getDDCs');
	    if (isset($ddcs) && !empty($ddcs)) {
	    	echo '<tr>';
	    	echo '<th>'.$this->transEsc('classification').': </th>';
	    	echo '<td>';
	    	foreach ($ddcs as $ddc) {
	    		echo '<a title="'.$ddc.'" href="'.$this->url('search-results').'?lookfor='.urlencode($ddc).'&type=classification&limit=20" rel="nofollow">';
	    		echo $this->escapeHtml($ddc).'<br />';
	    		echo '</a>';
	    	}
	    	echo '</td>';
	    	echo '</tr>';
	    }

	    // AK subjects
	    $akSubjects = $this->driver->tryMethod('getAkSubjects');
	    if (isset($akSubjects) && !empty($akSubjects)) {
	    	echo '<tr>';
	    	echo '<th>'.$this->transEsc('akSubjects').': </th>';
	    	echo '<td>';
	    	$linkArray = [];
	    	foreach ($akSubjects as $akSubject) {
	    		$link = '<a title="'.$akSubject.'" href="'.$this->record($this->driver)->getLink('subject', $akSubject).'" rel="nofollow">';
	    		$link .= trim($this->escapeHtml(str_replace(array('<', '>'), '', $akSubject)));
	    		$link .= '</a>';
	    		$linkArray[] = $link;
	    	}
	    	echo implode(', ', $linkArray);
	    	echo '</td>';
	    	echo '</tr>';
	    }

	    // Keyword chains
	    $allKeywordChains = $this->driver->tryMethod('getAllKeywordChains');
	    if (!empty($allKeywordChains)) {
	    	echo '<tr>';
	    	echo '<td colspan="2">';
	    	echo '<b>'.$this->transEsc('keyword_chains').'</b> <span class="akInfoTooltipOpener" data-aktooltiptitle="'.$this->transEsc('akTtKeywordChainTitle').'" data-aktooltiptext="'.$this->transEsc('akTtKeywordChainText').'"><i class="fa fa-info-circle akInfoTooltipInfo" aria-hidden="true"></i></span>';

	    	foreach ($allKeywordChains as $keywordChain) {
	    		// Get the array key of last element in a keyword chain
	    		$arrayKeys = array_keys($keywordChain);
	    		$lastElement = array_pop($arrayKeys);
	    		echo '<hr class="akKeywordChainsSeparator" />';
	    		foreach ($keywordChain as $key => $keyword) {
	    			$keyword = trim($keyword);
	    			echo '<a class="akKeywordChainLink" title="'.$this->escapeHtmlAttr($keyword).'" href="'.$this->record($this->driver)->getLink('subject', $keyword).'" rel="nofollow">'.trim($this->escapeHtml(str_replace(array('<', '>'), '', $keyword))).'</a>';
	    			if ($key != $lastElement) {
	    				echo ' <i class="fa fa-minus akKeywordChainArrow" aria-hidden="true"></i> ';
	    			}
	    		}
	    	}
	    	echo '</td>';
	    	echo '</tr>';

	    }


	    ?>











    <?php
    #######################################################################
    // TODO: Kontrolle weiter ab hier!!!
    #######################################################################
    ?>






	 <? $corporateAuthors = $this->driver->getCorporateAuthors(); if (!empty($corporateAuthors)): ?>
      <tr>
      	<th><?=$this->transEsc('Corporate Author')?>: </th>
      	<td>
      	 <? foreach($corporateAuthors as $corporateAuthor): ?>
         	<a property="creator" href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($corporateAuthor)?>&type=AllFields&limit=20"><?=$this->escapeHtml(str_replace(array('<', '>'), '', $corporateAuthor))?></a><br />
         <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>










<?php
/*
      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subjectLine" property="keywords">
            <? $subject = ''; ?>
            <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow"><?=trim($this->escapeHtml(str_replace(array('<', '>'), '', $subfield)))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>
*/
?>


      <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
        </td>
      </tr>
      <? endif; ?>



      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(null, null, 'count', $user_id); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <a id="tagRecord" class="btn btn-link modal-link pull-right flip" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>">
              <i class="fa fa-plus"></i> <?=$this->transEsc('Add Tag')?></a>
            </a>
            <?=$this->context($this)->renderInContext('record/taglist', array('tagList'=>$tagList, 'loggedin'=>$loggedin)) ?>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
