<? $list = $this->params->getSortList(); if (!empty($list)): ?>

<?php
// On "New items page" (Neuerwerbungen), remove relevance sorting because this is useless here.
if ($this->layout()->templateDir == 'search' && $this->layout()->templateName == 'newitemresults') {
	$urlQuery = $this->results->getUrlQuery(); // Get query variables. This returns a VuFind\Search\UrlQueryHelper
	$paramArray = $urlQuery->getParamArray(); // Get an array of the query parameters
	
	// Unset the relevance sort option if specified in AKsearch.ini	
	if (!$paramArray['relevance']) {
		unset($list['relevance']);
	}
}
?>

  <form class="form-inline" action="<?=$this->currentPath()?>" method="get" name="sort">
    <?=$this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/'));?>
    <label for="sort_options_1"><?=$this->transEsc('Sort')?></label>
    <select id="sort_options_1" name="sort" class="jumpMenu form-control">
      <? foreach ($list as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtmlAttr($sortType)?>"<?=$sortData['selected']?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
      <? endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>

