<?php 
	$email = (isset($this->profile['email'])) ? $this->profile['email'] : '';
	$phone = (isset($this->profile['phone'])) ? $this->profile['phone'] : '';	
	$phone2 = '';
	if (isset($this->profile['phone2'])) {
		$phone2 = $this->profile['phone2'];
	} else if (isset($this->profile['phonesAdditional'])) {
		$phone2 = (isset($this->profile['phonesAdditional'][0])) ? $this->profile['phonesAdditional'][0] : '';
	}
?>
<div>
    <table class="table table-striped">
	    <tbody>
	    	<tr>
	    		<th style="vertical-align: middle;"><?=$this->transEsc('email') ?> *</th>
	    		<td class="form-group"><input type="email" value="<?=$email?>" id="cudEmail" name="cudEmail" class="form-control" required aria-required="true" /><div class="help-block with-errors"></div></td>
	    	</tr>
	    	<tr>
	    		<th style="vertical-align: middle;"><?=$this->transEsc('phone') ?></th>
	    		<td class="form-group"><input type="text" value="<?=$phone ?>" id="cudPhone" name="cudPhone" class="form-control" /></td>
	    	</tr>
	    	<tr>
	    		<th style="vertical-align: middle;"><?=$this->transEsc('phone2') ?></th>
	    		<td class="form-group"><input type="text" value="<?=$phone2 ?>" id="cudPhone2" name="cudPhone2" class="form-control" /></td>
	    	</tr>
	    </tbody>
    </table>
</div>