<?php

// Get username to populate the form field
if (isset($this->username)) {
    $username = $this->escapeHtmlAttr($this->username);
} else if ($this->request->get('username')) {
    $username = $this->escapeHtmlAttr($this->request->get('username'));
} else {
    $username = '';
}

// Get eMail to populate the form field
// INFO: We set this to an empty string so that the user does have an effort before being able to click the submit button
//       and send the eMail again. This could save us some extra sending of eMails.
//$email = ($this->request->get('email')) ? $this->escapeHtmlAttr($this->request->get('email')) : '';
$email = '';

?>

<div>
    <table class="table table-striped">
	    <tbody>
			<tr>
	    		<th style="vertical-align: middle;"><?=$this->transEsc('Username') ?></th>
	    		<td class="form-group"><input type="text" value="<?=$username?>" id="username" name="username" class="form-control" required aria-required="true" /><div class="help-block with-errors"></div></td>
	    	</tr>
	    	<tr>
	    		<th style="vertical-align: middle;"><?=$this->transEsc('email') ?></th>
	    		<td class="form-group"><input type="text" value="<?=$email?>" id="email" name="email" class="form-control" required aria-required="true" /><div class="help-block with-errors"></div></td>
	    	</tr>
	    </tbody>
    </table>
</div>