<div>
    <table class="table table-striped">
	    <tbody>
	    	<tr>
	    		<th style="vertical-align: middle;"><?=$this->transEsc('Username') ?></th>
	    		<td class="form-group">USERNAME HERE</td>
	    	</tr>
	    	<tr>
	    		<th style="vertical-align: middle;"><?=$this->transEsc('new_password') ?></th>
	    		<td class="form-group"><input type="password" value="" id="newPassword" name="newPassword" class="form-control" required aria-required="true" <?=isset($this->passwordPolicy['minLength']) ? ' data-minlength="' . $this->passwordPolicy['minLength'] . '" data-minlength-error="' . $this->escapeHtmlAttr($this->translate('password_minimum_length', array('%%minlength%%' => $this->passwordPolicy['minLength']))) . '"' : ''?><?=isset($this->passwordPolicy['maxLength']) ? ' maxlength="' . $this->passwordPolicy['maxLength'] . '"' : ''?>/><div class="help-block with-errors"></div></td>
	    	</tr>
	    	<tr>
	    		<th style="vertical-align: middle;"><?=$this->transEsc('confirm_new_password') ?></th>
	    		<td class="form-group"><input type="password" value="" id="newPasswordConfirm" name="newPasswordConfirm" class="form-control" required aria-required="true" data-match="#newPassword" data-match-error="<?=$this->escapeHtmlAttr($this->translate('Passwords do not match'))?>"/><div class="help-block with-errors"></div></td>
	    	</tr>
	    </tbody>
    </table>
</div>