<?
    // Set up page title:
    $this->headTitle($this->translate('New Item Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('New Items') . '</li>';
?>
<h2><?=$this->transEsc('Find New Items')?></h2>
<form method="get" class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-3 control-label"><?=$this->transEsc('akPeriod')?>:</label>
    <div class="col-sm-9">
      <div class="btn-group" data-toggle="buttons">
            <?php
            foreach ($this->ranges as $key => $range) {
            	if ($range !== 'datepicker') {
            		echo '<label class="btn btn-primary'.(($key == 0) ? ' active' : '').'">';
            		echo '<input type="radio" name="range" id="newitem_range_'.$this->escapeHtmlAttr($key).'" value="'.$this->escapeHtmlAttr($range).'" '.(($key == 0) ? ' checked="checked"' : '').' />';
            	
            		$buttonText = null;
            		if ($range == 1) {
            			$buttonText = $this->transEsc('Yesterday');
            		} else if ($range == 7) {
            			$buttonText = $this->transEsc('lastWeek');
            		} else if ($range == 30 || $range == 31) {
            			$buttonText = $this->transEsc('lastMonth');
            		} else {
            			$buttonText = $this->transEsc('Past') . ' ' . $this->escapeHtml($range) . ' ' . $this->transEsc('Days');
            		}
            		echo $buttonText;
            	
            		echo '</label>';
            	} else {
            		// Add date picker (we use bootstrap-datepicker here: https://bootstrap-datepicker.readthedocs.io
            		echo '<label id="newitemDatepicker" class="btn btn-primary '.(($key == 0) ? 'active' : '').'">';
            			echo '<input id="newitemDatepickerRadio" type="radio" name="range" value="0" '.(($key == 0) ? ' checked="checked"' : '').'/>';
            			echo '<span id="newitemDatepickerText">'.$this->transEsc('akSelect').'</span>';
            		echo '</label>';
            	}
            }
            ?>
		
      </div>
    </div>
  </div>
  <? if (is_array($this->fundList) && !empty($this->fundList)): ?>
    <div class="form-group">
      <label class="col-sm-3 control-label" for="newitem_department"><?=$this->transEsc('Department')?>:</label>
      <div class="col-sm-9">
        <select id="newitem_department" name="department" size="10" class="form-control">
        <? foreach ($this->fundList as $fundId => $fund): ?>
          <option value="<?=$this->escapeHtmlAttr($fundId)?>"><?=$this->transEsc($fund)?></option>
        <? endforeach; ?>
        </select>
      </div>
    </div>
  <? endif; ?>
  
  <?php
  $newItemFilters = $this->newItemFilters; // Comes from SearchController->newitemAction() (there see createViewModel)
  if (is_array($newItemFilters) && !empty($newItemFilters)) {
  	foreach ($newItemFilters as $label => $values) {
  		$size = (count($values['values']) < 10) ? count($values['values']) : 10;
  		
  		echo '<div class="form-group">';
  			echo '<label class="col-sm-3 control-label">'.$this->transEsc($label).':</label>';
	  		echo '<div class="col-sm-9">';
		  		echo '<select id="newItemsFilter" multiple name="newItemsFilter['.$label.'][]" size="'.$size.'">';
		  		foreach ($values['values'] as $value) {
		  			echo '<option value="'.$value['solrfield'].':'.str_replace(':', '\:', $value['filtervalue']).'">'.$value['filterlabel'].'</option>';
		  		}
		  		echo '</select>';
	  		echo '</div>';
  		echo '</div>';
  	}
  	
  }
  	
  ?>
  
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Find')?>"/>
    </div>
  </div>
</form>